SELECT DISTINCT ?accession  WHERE{ 
  ?bioMat ppeo:hasAccessionName ?accession.

  ?s1 a ppeo:study; ppeo:hasEndDateTime ?d1.
  ?s2 a ppeo:study; ppeo:hasEndDateTime ?d2.
  ?s3 a ppeo:study; ppeo:hasEndDateTime ?d3.
  ?s4 a ppeo:study; ppeo:hasEndDateTime ?d4.
  ?s5 a ppeo:study; ppeo:hasEndDateTime ?d5.

  ?obsUnit1 a ppeo:observation_unit; 
	ppeo:partOf ?s1; 
	ppeo:hasBiologicalMaterial ?bioMat.
  ?obsUnit2 a ppeo:observation_unit; 
	ppeo:partOf ?s2; 
	ppeo:hasBiologicalMaterial ?bioMat.
  ?obsUnit3 a ppeo:observation_unit; 
	ppeo:partOf ?s3; 
	ppeo:hasBiologicalMaterial ?bioMat.
  ?obsUnit4 a ppeo:observation_unit; 
	ppeo:partOf ?s4; 
	ppeo:hasBiologicalMaterial ?bioMat.
  ?obsUnit5 a ppeo:observation_unit; 
	ppeo:partOf ?s5; 
	ppeo:hasBiologicalMaterial ?bioMat.
  
    filter(year(?d1) - year(?d2) = 1)
    filter(year(?d2) - year(?d3) = 1)
    filter(year(?d3) - year(?d4) = 1)
    filter(year(?d4) - year(?d5) = 1)
} 