PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix xsd:     <http://www.w3.org/2001/XMLSchema#> 
prefix schema:  <http://schema.org/> 
prefix owl:     <http://www.w3.org/2002/07/owl#> 
prefix skos:    <http://www.w3.org/2004/02/skos/core#> 
prefix oa:      <http://www.w3.org/ns/oa#> 
prefix ncbi:    <http://identifiers.org/taxonomy/> 
prefix dct:     <http://purl.org/dc/terms/> 
prefix frbr:    <http://purl.org/vocab/frbr/core#> 
prefix fabio:   <http://purl.org/spar/fabio/> 
prefix obo:     <http://purl.obolibrary.org/obo/> 
prefix bibo: <http://purl.org/ontology/bibo/> 
PREFIX d2kab: <http://ontology.inrae.fr/bsv/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix xsd:     <http://www.w3.org/2001/XMLSchema#>
prefix schema:  <http://schema.org/>
prefix owl:     <http://www.w3.org/2002/07/owl#>
prefix skos:    <http://www.w3.org/2004/02/skos/core#>
prefix oa:      <http://www.w3.org/ns/oa#>
prefix ncbi:    <http://identifiers.org/taxonomy/>
prefix dct:     <http://purl.org/dc/terms/>
prefix frbr:    <http://purl.org/vocab/frbr/core#>
prefix fabio:   <http://purl.org/spar/fabio/>
prefix obo:     <http://purl.obolibrary.org/obo/>
prefix bibo: <http://purl.org/ontology/bibo/>
prefix d2kab:   <http://ns.inria.fr/d2kab/>
prefix dc: <http://purl.org/dc/terms/>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>
PREFIX wikidata: <http://www.wikidata.org/entity/>
prefix d2kab-bsv:   <http://ontology.inrae.fr/bsv/ontology/>

SELECT distinct ?paper ?bsv ?taxLabel ?fcuCropName ?taxrefClass WHERE {
   {
    SELECT distinct ?paper ?taxon WHERE {       
      ?annot a oa:Annotation; oa:hasTarget [ oa:hasSource ?source ] ; oa:hasBody ?taxon .
      ?taxon a d2kab:Taxon; skos:prefLabel ?label .
      ?source frbr:partOf+ ?paper .
      ?paper a fabio:ResearchPaper ; dct:title ?source .
      FILTER(CONTAINS(?label, "Triticum aestivum"))
    }
    LIMIT 100
    }
    
   SERVICE <http://taxref.i3s.unice.fr/sparql> {
      ?taxrefClass owl:equivalentClass ?taxon ; rdfs:label ?taxLabel . 
   }
   ?fcuCropName taxref:candidateAlignment_eppo|taxref:candidateAlignment_geves ?taxrefClass .  
    
   SERVICE <http://ontology.inrae.fr/bsv/sparql> { 
      ?bsv a d2kab-bsv:Bulletin ; dul:isRealizedBy ?s ; dct:spatial ?w  ; dct:date ?date_bsv .
      ?aa a oa:Annotation ; oa:hasTarget [ oa:hasSource ?s ]  ; oa:hasBody ?fcuCropName .
   }      
}
LIMIT 100


 