prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#> .
prefix xsd:     <http://www.w3.org/2001/XMLSchema#> .
prefix schema:  <http://schema.org/> .
prefix owl:     <http://www.w3.org/2002/07/owl#> .
prefix skos:    <http://www.w3.org/2004/02/skos/core#> .
prefix oa:      <http://www.w3.org/ns/oa#> .
prefix ncbi:    <http://identifiers.org/taxonomy/> .
prefix dct:     <http://purl.org/dc/terms/> .
prefix frbr:    <http://purl.org/vocab/frbr/core#> .
prefix fabio:   <http://purl.org/spar/fabio/> .
prefix obo:     <http://purl.obolibrary.org/obo/> .
prefix bibo: <http://purl.org/ontology/bibo/> .
prefix d2kab:   <http://ns.inria.fr/d2kab/> .

SELECT distinct  ?doc ?gene ?variety  
WHERE {
?rel1 d2kab:hasVariety ?aVariety ;
    d2kab:hasPhenotype ?aPhenotype.
 
?aVariety a oa:Annotation ;
            oa:hasTarget ?t1 ;
            oa:hasBody ?Variety .
?t1 oa:hasSource ?d1 .
?Variety a d2kab:Variety ;
        skos:prefLabel ?variety.
?aPhenotype a oa:Annotation ;
            oa:hasTarget ?t2 ;
            oa:hasBody ?Phenotype .
?t2 oa:hasSource ?d2 .
?e2 skos:prefLabel "pathogen resistance" ;
    skos:narrower* ?Phenotype .
?aTaxon a oa:Annotation ;
        oa:hasTarget ?t ;
        oa:hasBody ?Taxon.
?t oa:hasSource ?d .
?Taxon a d2kab:Taxon ;
        skos:prefLabel "Triticum aestivum".
?aGene a oa:Annotation ;
        oa:hasTarget ?t3;
        oa:hasBody ?Gene.
?t3 oa:hasSource ?d3 .
?Gene a d2kab:Gene ;
        skos:prefLabel ?gene.
?d1 frbr:partOf+ ?doc .
?d2 frbr:partOf+ ?doc .
?d3 frbr:partOf+ ?doc .
?d frbr:partOf+ ?doc .
?doc  a fabio:ResearchPaper .
}