prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#> .
prefix xsd:     <http://www.w3.org/2001/XMLSchema#> .
prefix schema:  <http://schema.org/> .
prefix owl:     <http://www.w3.org/2002/07/owl#> .
prefix skos:    <http://www.w3.org/2004/02/skos/core#> .
prefix oa:      <http://www.w3.org/ns/oa#> .
prefix ncbi:    <http://identifiers.org/taxonomy/> .
prefix dct:     <http://purl.org/dc/terms/> .
prefix frbr:    <http://purl.org/vocab/frbr/core#> .
prefix fabio:   <http://purl.org/spar/fabio/> .
prefix obo:     <http://purl.obolibrary.org/obo/> .
prefix bibo: <http://purl.org/ontology/bibo/> .
prefix d2kab:   <http://ns.inria.fr/d2kab/> .

select distinct ?docu where {
  ?x a oa:Annotation; 
   oa:hasTarget ?y;
   oa:hasBody ?e .
  ?y oa:hasSource ?d .
  ?e skos:prefLabel ?a .
  ?d frbr:partOf+ ?docu .
  ?docu a fabio:ResearchPaper .
  filter (?a =   "Lr34") .
}