prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#> .
prefix xsd:     <http://www.w3.org/2001/XMLSchema#> .
prefix schema:  <http://schema.org/> .
prefix owl:     <http://www.w3.org/2002/07/owl#> .
prefix skos:    <http://www.w3.org/2004/02/skos/core#> .
prefix oa:      <http://www.w3.org/ns/oa#> .
prefix ncbi:    <http://identifiers.org/taxonomy/> .
prefix dct:     <http://purl.org/dc/terms/> .
prefix frbr:    <http://purl.org/vocab/frbr/core#> .
prefix fabio:   <http://purl.org/spar/fabio/> .
prefix obo:     <http://purl.obolibrary.org/obo/> .
prefix bibo: <http://purl.org/ontology/bibo/> .
prefix d2kab:   <http://ns.inria.fr/d2kab/> .

select distinct ?var  ?doc where {
  ?rel1 d2kab:hasVariety ?ano1 ;
           d2kab:hasPhenotype ?ano2 .
  
  ?ano1 a oa:Annotation ;
             oa:hasTarget ?t1 ;
             oa:hasBody ?e1 .
  ?t1 oa:hasSource ?d1 .

  ?e1 a d2kab:Variety ;
         skos:prefLabel ?var.

  ?ano2 a oa:Annotation ;
             oa:hasTarget ?t2 ;
             oa:hasBody ?e2 .
  ?t2 oa:hasSource ?d2 .

  ?e2 skos:prefLabel ?a ;
      a d2kab:Phenotype .

  ?d1 frbr:partOf+ ?doc .
  ?d2 frbr:partOf+ ?doc . 
  ?doc  a fabio:ResearchPaper .
  filter (?a = "crop yield") .
}